### ISSUE TITLE
markdownItalic pattern is confused by "\_"

### ISSUE THREAD

**Issue by justinmk** [tpope/vim-markdown#102]
Reported at https://github.com/neovim/neovim/issues/3230, creating an issue here to get feedback.

With text shown below, the syntax match is confused:

<img width="629" alt="68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3130333334353230392f53637265656e73686f74732f53637265656e73686f74253230323031352d30382d323425323031332e31362e32392e706e67" src="https://cloud.githubusercontent.com/assets/1359421/18987141/92d61b20-8700-11e6-8999-316efc370860.png">

[Suggested fix](https://github.com/neovim/neovim/issues/3230#issuecomment-136310537) is to add  `skip` to the syntax pattern:

```
syn region markdownItalic start="\S\@<=_\|_\S\@=" skip="\\_" end="\S\@<=_\|_\S\@=" keepend contains=markdownLineStart
```

**Comment by tpope** [comment]
This feels like a job for `contains=markdownEscape`, but with italics rendered as inverse and the default `Special` negating that with bold, it's ugly to the point of looking broken. We'll use `skip` for now.
