### ISSUE TITLE
Error detected while processing FileType Auto commands for "markdown"

### ISSUE THREAD

**Issue by smalike** [tpope/vim-markdown#104]
Error detected while processing FileType Auto commands for "markdown":
E117: Unknown function: textobj#sentence#init
E117: Unknown function: textobj#quote#init

**Comment by theptrk** [comment]
Hi! Did you ever figure this out?

**Comment by tpope** [comment]
This is almost certainly another plugin which fires on Markdown files, not vim-markdown itself. `textobj#` appears nowhere in the vim-markdown source.

**Comment by theptrk** [comment]
Yeah, I'm almost positive these are from a stock vim configuration, likely `spf13-vim` and its coming from these lines https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L484

I fixed my issue, forgot how, but this can likely be closed as a vim-markdown issue
