### ISSUE TITLE
Frontmatter syntax highlighting is not correct

### ISSUE THREAD

**Issue by boompig** [tpope/vim-markdown#112]
This is what markdown's frontmatter looks like with current version of vim-markdown's syntax highlighting.

<img width="692" alt="screen shot 2017-03-12 at 3 11 49 am" src="https://cloud.githubusercontent.com/assets/2791268/23830867/ade39658-06d1-11e7-9aa2-dd23502b43e1.png">

Note the different highlighting of the last front-matter line from the first few.

This is the case using the syntax file in commit 3c2215bfed1de1251927fbc94b2631ca27c2958f, which is the latest commit in master at the time I am creating this issue.

**Comment by RichardDooling** [comment]
Add these two lines to your .vim/after/syntax/markdown.vim files

syntax include @Yaml syntax/yaml.vim
syntax region yamlFrontmatter start=/\%^---$/ end=/\v^%(\.{3}|\-{3})$/ keepend contains=@Yaml

**Comment by boompig** [comment]
I found what worked for me was:

```vim
unlet b:current_syntax
syntax include @Yaml syntax/yaml.vim
syntax region yamlFrontmatter start=/\%^---$/ end=/^---$/ keepend contains=@Yaml
```

I'm not sure if YAML frontmatter is part of the Markdown spec, or if there is such a thing as a Markdown spec. But if it's standard practice to add frontmatter to markdown, then this should probably go into the syntax file.

**Comment by RichardDooling** [comment]
I think YAML is YAML and Markdown is Markdown. A tool like Pandoc uses both and allows --- or ... for marking the end of the frontmatter. But I don't think YAML is part of the CommonMark spec

http://spec.commonmark.org/0.26/

It's been discussed here

https://talk.commonmark.org/t/metadata-in-documents/721/48

And so far the idea is to keep Markdown as simple as possible. So YAML is more like an add-on for tools like Jekyll and Pandoc. 

John MacFarlane who made Pandoc also heads up the CommonMark spec. You could maybe chip and provide ideas, they are still formulating the eventual final spec.

Rick

**Comment by tpope** [comment]
See #105.

**Comment by jrwrigh** [comment]
For documentation's sake, if you need both YAML and TOML front matter capabilities (which is true if you're working with something like Hugo), this is what I have:

```vim
unlet b:current_syntax
syntax include @Toml syntax/toml.vim
syntax region tomlFrontmatter start=/\%^+++$/ end=/^+++$/ keepend contains=@Toml
syntax include @Yaml syntax/yaml.vim
syntax region yamlFrontmatter start=/\%^---$/ end=/^---$/ keepend contains=@Yaml
```

where `---` marks a YAML syntax front matter and `+++` marks a TOML front matter.
