### ISSUE TITLE
Conceal does not appear to work on code fences or code blocks.

### ISSUE THREAD

**Issue by jordwalke** [tpope/vim-markdown#114]
All of `vim-markdown`'s conceal feature works well for me accept anything related to code fences or code blocks. I'm not sure if this is supposed to be supported, but I thought I would ask since it wasn't clear from the docs. Here's my vimrc:

```
Plug 'tpope/vim-markdown'
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'javascript', 'reason', 'ocaml']
set conceallevel=2
set concealcursor=nc
let g:markdown_syntax_conceal=1
```

It would be really great to get concealing of those triple backticks and yet still have syntax highlighted according to the specified language.

**Comment by tpope** [comment]
Current implementation is bold and italic delimiters only. Extending to code blocks might be really easy if you want to take a shot at it.
