### ISSUE TITLE
How to disable automatic table formatting?

### ISSUE THREAD

**Issue by tonglil** [tpope/vim-markdown#120]
I don't want to be formatting tables of projects that choose not to format their tables (aka let GitHub take care of it).

How can I disable the automatic formatting?

**Comment by tpope** [comment]
There is no support for tables (which aren't a core Markdown feature), so I'm not sure what you are referring to.

**Comment by tonglil** [comment]
Mm, thanks. I'll investigate further what is causing the table to indent. Thanks!
