### ISSUE TITLE
Highlighting gets confused with multiple levels of square brackets

### ISSUE THREAD

**Issue by joel-porquet** [tpope/vim-markdown#129]
Hi,

[Remark](https://github.com/gnab/remark), which I use a lot for creating slides, allows to apply HTML classes to any content (see https://github.com/gnab/remark/wiki/Markdown#content-classes). For example, I defined two classes "hcol" and "rcol" so that I can divide my slides into two columns and put contents in them.

The problem appears when I include a image within one of these content classes, with the following syntax:
```
.lcol[
![:scale 60%](images/array.svg)
]
```
In that case, the markdown coloration gets completely confused and starts coloring everything after line that includes the image in purple (including the closing bracket on the last line).

Any ideas how to fix that?
Thanks!

**Comment by cbcoutinho** [comment]
Possibly related to the issue I originally opened neovim/neovim#9343 regarding multiple layers of brackets. That issue was based on image captions containing square brackets (latex citations), but it seems related to this one.

**Comment by ascherer** [comment]
A similar problem occurs with a link in a footnote:
```
Grundelemente^[Im [Anhang](#anhang) erfährst du, … kannst.] und ….
```
The blue and underlined link text starting with `Im` doesn't stop after `kannst.`, but continues over `und` (almost) until the end of the text file.

**Comment by ascherer** [comment]
A workaround for _my_ case is to use the alternative syntax for links:
```
Grundelemente^[Im [Anhang] erfährst du, … kannst.] und ….

[Anhang]: #anhang
```

**Comment by fditraglia** [comment]
I'm having this problem as well on vim version 8.0 on Ubuntu 18.04.3 LTS. I like to use square brackets to set off links related to a title, e.g.

`Title of paper [[link1](http://link1.com), [link2](http://link2.com)]`

**Comment by tpope** [comment]
Looks like one level of bracket nesting isn't too hard to accommodate.

**Comment by fditraglia** [comment]
Fantastic! Thanks.
