### ISSUE TITLE
Hightling goes away when I indent text

### ISSUE THREAD

**Issue by davejones444** [tpope/vim-markdown#130]
Title. I installed vim-markdown with vim-plug and I'm using the recommended settings on my .vimrc:

autocmd BufNewFile,BufReadPost *.md set filetype=markdown
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
let g:markdown_syntax_conceal = 0
let g:markdown_minlines = 100

The file has the .md extension.

Otherwise (without intending) it works very well.

I'm using Vim 8 on updated MX Linux 17.

**Comment by tpope** [comment]
Indenting text makes it a code block.

**Comment by davejones2** [comment]
Yeah, sorry about that. I didn't know that about markdown.
