### ISSUE TITLE
Second line in nested list item becomes a code block

### ISSUE THREAD

**Issue by marlun** [tpope/vim-markdown#145]
I've read the other issues with newlines but not understood if I could fix this myself. If I nest a list item and it gets longer than 1 line it's highlighted as a code block:

    * Listitem
      - Nested list item with a long text
        this becomes highlighted as code block
      - Just another item
    * Just another item

Could this be fixed or is it just a result of a compromise needed to be done with regex highlighting of markdown?

**Comment by tpope** [comment]
It's a compromise. I imagine a more elaborate compromise that supports this use case would be possible, by defining a "2 space list item" that can only be followed by a "6 space code block", or whatever the appropriate logic is, but it's not a rabbit hole I personally have time to go down.

**Comment by marlun** [comment]
OK, I'll close the issue since it's not a big deal and I got my answer, thanks!
