### ISSUE TITLE
Folding completly broken while editing code blocks

### ISSUE THREAD

**Issue by Grueslayer** [tpope/vim-markdown#147]
While editing inside code blocks the sections automatically folds:

Using a stripped down .vimrc 

~~~vim
abclear
mapclear
imapclear
au!
set all&

set   encoding=utf-8
scriptencoding utf-8
set   fileencodings=utf-8,ucs-bom,latin1

if has("win32")
	let g:vimuserrtp = glob("~\\vimfiles")
else
	let g:vimuserrtp = glob("~/.vim")
endif
call plug#begin(g:vimuserrtp . '/bundle')
Plug 'tpope/vim-markdown'
call plug#end()

filetype off
filetype plugin indent on
syntax on
~~~

and  a small markdown file

```md
# Level 1

Lore ipsum xxxx

## Level 2

Lore ipsum xxxx

### Level 3

~~~
12456789012345
12456789012345
12456789012345
~~~


```
going to the first code block line and after pressing four times the "x" key on some of the digits (which deletes 4 characters) the last Level gots folded! Another "x" then deletes the complete section!

**Comment by tpope** [comment]
Can't reproduce. `~~~` isn't a code block. Folding is disabled by default, and your example vimrc doesn't enable it. I feel like you left some stuff out?

**Comment by Grueslayer** [comment]
Hi,
of course `~~~` is a code block. This was for long time introduced and is used by github all time [https://github.github.com/gfm/#fenced-code-blocks](https://github.github.com/gfm/#fenced-code-blocks).

But you are right with the folding, I need to check out where the source is of that enabling, it it isn't by your Plugin.

**Comment by tpope** [comment]
Maybe it's been around for a long time but I can find no evidence of that. The spec you reference is just 2 years old. The instructions you get when you click on the icon by the icon field - https://guides.github.com/features/mastering-markdown/ - do not mention it. More importantly, vim-markdown does not support it, and nobody has ever requested it. And people aren't shy about requesting all sorts of dumb markdown extensions.

**Comment by Grueslayer** [comment]
I do not want to offend you or something like that. I always use the tildes for fenced blocks and never use back ticks, cause it's so much easier to write on a German keyboard. I do not know any implementation not supporting it. The [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/) implementation is quite old and already support this.
Don't want to force you to do anything, keep going on like you like. I like your plugins.

**Comment by tpope** [comment]
I mean I wouldn't even be opposed to supporting it, I'm just miffed at having never seen it.
