### ISSUE TITLE
Syntax highlighting breaks when using {:target="_blank"} on links

### ISSUE THREAD

**Issue by nickjj** [tpope/vim-markdown#150]
Here's a test case where it fails:

```markdown
[hello](https://example.com){:target="_blank"}

Oops, this is colored up incorrectly as if it's the anchor's text.
```

If you adjust the above to be `[hello](https://example.com)` then things work as expected but then it's missing the attribute to set the target.

**Comment by tpope** [comment]
What I'm seeing is everything after the `_` highlighted as italics. It's also how GitHub is highlighting it. I assume the `{}` notation is some sort of Markdown extension. I'm not sure what to do about that, but I generally don't support extensions because there's a million of them.

**Comment by nickjj** [comment]
Here's what it looks like in my editor. The left side is bad and the right side is good:

![image](https://user-images.githubusercontent.com/813219/69484267-3f6ab200-0dff-11ea-9ae9-4d2938aaf8f4.png)

Adding a target and other attributes like that is part of GitHub's style of markdown. I'm not sure why their own highlighting is showing everything in italics. Note that it's not just the _blank in italics. It's the rest of the document. This is very disruptive if you have one of those links on line 3 of a 300 line file because it messes up the coloring for everything.

Plasticboy's markdown plugin handles this functionality correctly but it has a bunch of other issues (which is ultimately why I ended up trying out your plugin).

**Comment by tpope** [comment]
I don't have any suggestions for how you can patch this without breaking other use cases. But if you just want to fix it locally, there's a million not very hard ways you can do so in `after/syntax/markdown.vim`. Here's a simple one that disables underscore italics entirely:

```vim
syn match markdownUnderscoreNoop /_/
```

**Comment by gerardbm** [comment]
I'm sorry for commenting in a closed issue. I only want to show my solution for others:
https://github.com/gerardbm/vim-atomic/commit/89787fd5434db43cc3b6e9e0c27d5bc386538800

Regards.
