### ISSUE TITLE
Commit 9c2133fef0ff4ec082c8215b1abd405bd1ee098d breaks italics rendering in `nvim`

### ISSUE THREAD

**Issue by Pseudomanifold** [tpope/vim-markdown#151]
Dear all,

the recent commit 9c2133fef0ff4ec082c8215b1abd405bd1ee098d breaks italics rendering for me in `nvim`: when writing one word in italics using '\*', the highlighting never stops afterwards. See this screenshot for details:

![vim](https://user-images.githubusercontent.com/11440811/70733965-9cc19700-1d0b-11ea-8a3c-e26ac3a6bd8a.png)

System information:

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

The same issue occurs with `vim`. I am assuming that the referenced commit is at fault because it was the last time the Markdown formatting was modified. As a small workaround, I removed the `skip` and replaced it by `keepend` again.

**Comment by Pseudomanifold** [comment]
Thanks for the quick fix!

**Comment by tpope** [comment]
Unfortunately the broken version is in Vim 8.2. 😩
