### ISSUE TITLE
Bold with double asterisks syntax

### ISSUE THREAD

**Issue by zealotrush** [tpope/vim-markdown#153]
The last asterisk in `**bold**` is probably recognized as italic marker, and all text following it are also italic. Using `__bold__` doesn't have this problem.

I'm using **Vim 8.2.100**.

<img width="499" alt="vim-markdown" src="https://user-images.githubusercontent.com/2275580/72345096-ceb08980-370d-11ea-88ea-c415824c7d55.png">

**Comment by tpope** [comment]
Should be fixed on master, report back if not.

**Comment by Aaronmsv** [comment]
I had the same problem with the built-in version of Vim, using the latest master fixed the issue indeed.
