### ISSUE TITLE
g:markdown_folding = 1 and g:javaScript_fold = 1 set foldmethod to syntax 

### ISSUE THREAD

**Issue by Konfekt** [tpope/vim-markdown#154]
If the `vimrc` contains

```vim
let g:markdown_folding = 1
let g:javaScript_fold = 1
```

then `set filetype=markdown` and `set foldmethod?` gives the output

```vim
foldmethod=syntax
        Impostata l'ultima volta da /usr/share/vim/vim80/syntax/javascript.vim
```

in Vim 8.0. Instead, expected is 

```vim
foldmethod=expr
```

**Comment by Konfekt** [comment]
A workaround is adding to the `vimrc` the autocmd

```vim
autocmd FileType markdown setlocal foldmethod=expr
```

Curiously, adding `setlocal foldmethod=expr` to `ftplugin/markdown.vim` or `after/ftplugin/markdown.vim` does not solve the issue.

**Comment by Konfekt** [comment]
Same issue occurs if `g:ruby_fold = 1` is set. Other fold methods do not seem to influence. Though it seems to be an issue due to the syntax highlighting of fenced languages, `let g:markdown_fenced_languages = []` does not solve the issue.

**Comment by Konfekt** [comment]
The same issue applies to the `foldtext` value. Reopen or post a new issue?

**Comment by tpope** [comment]
A PR would be ideal.

**Comment by Konfekt** [comment]
The same issue applies to every other option set in some `ftplugin\html.vim` file, say setting `&makeprg` to `tidy` in `~/.vim/ftplugin/html.vim`. 

Is there a generic solution?

**Comment by tpope** [comment]
No generic solution I can think of, and if there was, I'm not convinced we would want to use it. Markdown is _basically_ a superset of HTML, so sometimes it should inherit HTML behaviors.

**Comment by Konfekt** [comment]
So `&makeprg` (say set to pandoc for markdown, tidy for html) is another exception to be reverted by hand in `markdown.vim`?

**Comment by tpope** [comment]
A generic solution on _your_ end would be `if &filetype ==# 'html'` on anything you don't want inherited by other file types.

**Comment by Konfekt** [comment]
Thank you! Prepending a line `if &filetype !=# 'javascript' | finish | endif` / `if &filetype !=# 'html' | finish | endif` to all `ftplugin/javascript.vim` / `ftplugin/html.vim` files seems to work.
