### ISSUE TITLE
Markdown: fenced code blocks

### ISSUE THREAD

**Issue by cup** [tpope/vim-markdown#156]
Fenced code blocks are defined as:

> A code fence is a sequence of at least three consecutive backtick characters
> (<code>&#x60;</code>) or tildes (`~`).

This is in the current Markdown spec (Apr 2019), and even back to the oldest
spec (Oct 2014):

- https://spec.commonmark.org/0.29#fenced-code-blocks
- https://spec.commonmark.org/0.5#fenced-code-blocks

However Vim-MarkDown only seems to define backticks with inline code:

https://github.com/tpope/vim-markdown/blob/f35c43c535af40dc045d55dd459969b6f31d4128/syntax/markdown.vim#L107-L109

Doesnt define tilde use at all, and only recognizes the indented style of code
blocks:

https://github.com/tpope/vim-markdown/blob/f35c43c535af40dc045d55dd459969b6f31d4128/syntax/markdown.vim#L73

Is this the case or am I overlooking something?

**Comment by cup** [comment]
https://github.com/vim/vim/issues/5660

**Comment by cup** [comment]
Looks like I misread the code. This covers fenced code blocks:

https://github.com/tpope/vim-markdown/blob/f35c43c535af40dc045d55dd459969b6f31d4128/syntax/markdown.vim#L109

but it only cover Backtick and not Tilde. So as a workaround Backtick can be
used.

**Comment by tpope** [comment]
There have been requests for tilde delimiters before, but they were always contextualized as being part of some non-standard extension. I didn't realize they were widely supported. We should definitely support them too.

**Comment by cup** [comment]
I think its a one line change - I can work up a pull request if thats acceptable

**Comment by tpope** [comment]
Sounds good.

**Comment by cup** [comment]
Given the Sublist issue is WONTFIX, I dont motivation now to fix this. No disrespect, but I am quite surprised that a project as mature as Vim is using a MarkDown highlighter with so many issues.

I do appreciate the responses. I think the better use of my time will be to recommend to the Vim team, another MarkDown repo with robust support.

**Comment by tpope** [comment]
Did you miss the part where I said "patches welcome" or are you just an entitled asshole that thinks I owe you a fix?

**Comment by cup** [comment]
@tpope thanks for your response.

Note that I have reported you to GitHub admins for inappropriate conduct.

I wasnt disrespectful in my comment, so your reply is uncalled for. To be
clear, as youve said you dont own me anything.

If you notice carefully I didnt ask for anything, I merely gave my views on the
current state of this project. I like to use an editor with syntax
highlighting, and MarkDown is one of the languages I write with. I only
started using Vim recently and already discovered 2 issues with the MarkDown
highlighter (this repo). Its clear that this repo is not a good fit for my use
case, and I would argue the larger Vim community, and I plan to make that
known.

Take care

**Comment by tpope** [comment]
Just because you were polite doesn't mean you were respectful.

**Comment by BatmanAoD** [comment]
@cup Just to be clear, CommonMark is not "the Markdown spec". It was intended to be that, but the original author of markdown objected.
