### ISSUE TITLE
Sublist items treated as code

### ISSUE THREAD

**Issue by cup** [tpope/vim-markdown#157]
Markdown defines a list like this:

> `M` is a list marker of width `W` followed by `1 ≤ N ≤ 4` spaces
>
> [...]
>
> and indenting subsequent lines of `Ls` by `W + N` spaces
>
> [...]
>
> A sublist must be indented the same number of spaces a paragraph would need
> to be in order to be included in the list item.

https://spec.commonmark.org/0.29#list-items

Which means that if you have a list like this:

~~~
- Sun
- Mon
- Tue
- Wed
~~~

Then `W + N` equals `1 + 1..4` equals `2..5`. It follows that subsequent lines
with list marker, indented in this range should be considered sublists.
Example:

~~~
- Sun
  - Day
- Mon
   - Day
- Tue
    - Day
- Wed
     - Day
~~~

The issue is that regardless of depth, with Vim Markdown any list item starting
with 5 or more spaces is treated as code rather than a sublist.

**Comment by tpope** [comment]
This was a compromise. Patches welcome.

**Comment by cup** [comment]
FYI this works as expected:

https://github.com/plasticboy/vim-markdown/blob/da5a7ac9/syntax/markdown.vim#L112-L114

Could maybe replace this:

https://github.com/tpope/vim-markdown/blob/296eeaa8877528fae45e89a9013c5a8d317deef1/syntax/markdown.vim#L76
