### ISSUE TITLE
Folding folds bash comments in code fences

### ISSUE THREAD

**Issue by rnmhdn** [tpope/vim-markdown#161]
<pre>
### section

```sh
echo 1

### section
echo 2
echo 3
```
### section
</pre>

**Comment by nevesnunes** [comment]
Same applies for other languages using `#` as the start of a comment.

I've found that `foldexpr` can easily become a performance issue. For example, with these validations:

```vim
function! s:NotCodeBlock(lnum) abort
  let id = synID(v:lnum, 1, 1)
  let attr = synIDattr(id, 'name')
  return attr !=# 'markdownCode' && attr !=# 'mkdCode' && attr !~# '.*Comment'
endfunction
```

I get noticeable delays while typing on a 3000 line file with around 30 code blocks. A workaround to reduce the times when `foldexpr` is called is to use the [FastFold plugin](https://github.com/Konfekt/FastFold).

Are there other alternatives that avoid these delays?

**Comment by davidsierradz** [comment]
Why not?:
```viml
function! s:NotCodeBlock(lnum) abort
  let id = synID(v:lnum, 1, 1)
  let attr = synIDattr(id, 'name')
  return attr !=# 'markdownCode' && attr !=# 'markdownCodeBlock'
endfunction
```
