### ISSUE TITLE
Don't Load User's ftplugin_html

### ISSUE THREAD

**Issue by dylnmc** [tpope/vim-markdown#166]
1. `vim README.md`
2. `~/.vim/after/ftplugin/html.vim` is loaded causing issues

what is this??

- https://github.com/vim/vim/blob/master/runtime/ftplugin/markdown.vim#L10
- https://github.com/tpope/vim-markdown/blob/master/ftplugin/markdown.vim#L10

maybe change to `source $VIMRUNTIME/ftplugin/html.vim` or something. I have `inoremap <buffer> ...` in `~/.vim/after/ftplugin/h
tml.vim`. I don't want html mappings in markdown. Markdown *isn't even close* to html/xml formatting.

https://github.com/vim/vim/issues/6354

**Comment by tpope** [comment]
Markdown is effectively a superset of HTML. You can use any valid HTML in it.

This is easy to guard against on your end, add this to your after file:

```vim
if &filetype ==# 'markdown'
  finish
endif
```

**Comment by dlejay** [comment]
The issue brought by @dylnmc is a valid one.

Even if HTML is a subset of Markdown, nobody expects user defined behaviour for HTML files to apply to the whole of Markdown files automatically. The user – me – is being surprised by the behaviour.

Example : I setup ALE to use `prettier` to format my HTML and auto-format on save. All of a sudden, my `.md` files get messed up. And I need to waste a long time to debug the issue : “do I have setup ALE in markdown.vim ? Does ALE use a default formatter if it detects it ?” etc etc. Just to realise that the system’s `markdown.vim` sources _my own_ user defined `html.vim`.

Please do not source user defined HTML settings by default.
