### ISSUE TITLE
Folding is undocumented

### ISSUE THREAD

**Issue by fancsali** [tpope/vim-markdown#170]
As the title suggests; I found out there's folding by browsing the code. It would be nice, if the documentation would also mention it.

**Comment by anthony-geoghegan** [comment]
This plugin provides only syntax highlighting for Markdown files and does not *add* support for folding.

It sets neither a `foldmethod` nor a `foldtext`: these settings only appear in the source as a way of preventing their values being over-written if a syntax file is loaded for one of the configured fenced languages. See https://github.com/tpope/vim-markdown/issues/154 for further context.

If you’d like a plugin that provides folding support, I’d suggest https://github.com/masukomi/vim-markdown-folding

I think this issue can be closed as not applicable.

**Comment by tpope** [comment]
Documentation is now upstream: https://github.com/vim/vim/blob/f4fcedc59d4cc5ae6b5270a933e8377030283c1c/runtime/doc/filetype.txt#L632-L635

**Comment by anthony-geoghegan** [comment]
I only just realised that folding *is* provided by this plugin and after a few experiments, I was about to suggest a pull request to add the same documentation to this project’s README.  Then I remembered that https://github.com/tpope/vim-markdown/pull/135 includes various improvements for the README – and this is one of them.
