### ISSUE TITLE
markdownCode style

### ISSUE THREAD

**Issue by 89z** [tpope/vim-markdown#174]
I noticed that code delimiters have style:

https://github.com/tpope/vim-markdown/blob/855b8915e0857f90cee180e1753ce1910d71c5b1/syntax/markdown.vim#L175

but it seems the text inside does not, either inline or block. Would you be open to adding style to these? I was thinking String style, but pretty much anything other than the current black on white would be better. I found example here:

~~~vim
HtmlHiLink mkdCode          String
~~~

https://github.com/plasticboy/vim-markdown/blob/8e5d86f7/syntax/markdown.vim#L162

**Comment by tpope** [comment]
This was a deliberate stylistic choice so that inline code and code blocks would match.

**Comment by 89z** [comment]
https://github.com/tpope/vim-markdown/pull/175
