### ISSUE TITLE
Conceal Headings (h1 to h6)

### ISSUE THREAD

**Issue by Bowuigi** [tpope/vim-markdown#180]
Is it possible to conceal the headings? Even if it only works on a single line.

If it is possible, how?

**Comment by jcla1** [comment]
Not at the moment, at least not easily. You can achieve the effect by adding [these lines](https://github.com/tpope/vim-markdown/blob/59a551feb24325498a5cf3a7f7fe4565361c1193/syntax/markdown.vim#L77-L82) to your vimrc and appending `concealends` (or `conceal` if you'd like the complete heading to be invisible for whatever reason) to each of them.

**Comment by Bowuigi** [comment]
Thank you! Should I close the issue?

**Comment by jcla1** [comment]
(I would, as I wouldn't consider even the option of concealing the heading delimiters a fit feature for vim-markdown, as otherwise you'd hardly be able to distinguish between different heading levels.)

**Comment by Bowuigi** [comment]
Got it, thank you!
