### ISSUE TITLE
Fix links display in markdown tables

### ISSUE THREAD

**Issue by jdorel** [tpope/vim-markdown#182]
In markdown tables, the display of links breaks the display of tables. With the following text :
![image](https://user-images.githubusercontent.com/20277513/136093743-f4b5ee05-6a70-4648-8b7b-112885e4b251.png)
The table is displayed as this :
![image](https://user-images.githubusercontent.com/20277513/136093880-6f86700d-b230-4942-abbc-c4c678e33370.png)

Would it be possible to replace the hidden characters with an equivalent amount of space (only in tables) to keep formating adequate ?

Note: I'm using vim-table-mode to automatically resize the table, so manually fixing the spaces is not an option

Thanks for all the hard work

**Comment by tpope** [comment]
No, Vim does not support that. Conceal is supported due to popular demand, but I personally recommend against using it, for reasons like this.

**Comment by AdrienLemaire** [comment]
Has the feature been implemented after #158, then removed at some point since this issue ? I cannot figure this out.

Using tpope/vim-markdown b78bbce3371a2eb56c89f618cd4ab2baadc9ee61 , I cannot see any link concealed. A feature I appreciated when using gabrielelana/vim-markdown.

**Comment by tpope** [comment]
No, it's never been supported for links. OP must have been using some other plugin.
