### ISSUE TITLE
markdownCodeBlock style

### ISSUE THREAD

**Issue by jxu** [tpope/vim-markdown#188]
I put the most recent version of the syntax file in my `~/.vim/syntax/`. Why does inline code have coloring but not code blocks?

**Comment by tpope** [comment]
Neither has coloring by default. Only the backticks themselves do.

**Comment by jxu** [comment]
What is the design rationale for this? Shouldn't code portions be highlighted?

**Comment by tpope** [comment]
1. Some code blocks (triple backtick ones to be specific) can have syntax highlighting, and those look uglier when you stack a base color on top of them.
2. Detecting indented code is impossible to do 100% reliably, and highlighting it would only draw attention to when it gets it wrong.

**Comment by jxu** [comment]
Is indented code not just four spaces on a newline? Also I haven't seen syntax highlighting in my fenced code blocks so maybe I need some other plugin for that.

**Comment by tpope** [comment]
> Is indented code not just four spaces on a newline?

Not when bulleted lists are involved. The current implementation erroneously detects some nested lists as code blocks.

> Also I haven't seen syntax highlighting in my fenced code blocks so maybe I need some other plugin for that.

See the README.
