### ISSUE TITLE
Reference links highlight

### ISSUE THREAD

**Issue by samarulmeu** [tpope/vim-markdown#189]
I hope this is the right place for the issue I encounter. I must mention that I do not use specifically the vim-markdown as plugin, only plain vim.

So, in the [official markdown specifications](https://daringfireball.net/projects/markdown/syntax#link) are defined what are called *reference-style links* that look something like `This is [an example][id] reference-style link` with the `id` defined later `[id]: http://example.com/  "Optional Title Here"`.

The problem is with the way that reference links are rendered as you can see from this screenshot. 

![Screenshot_2022-05-03_11-09-44](https://user-images.githubusercontent.com/39216570/166422146-55ca55c2-f3d9-4eb6-9055-2764f0247a6b.png)

The footnote explanation is nicely displayed, but for the reference only the first word (if not a link) is highlighted. Maybe a regex will check if a reference contains a link or not.

Thank you for your help and understanding!

**Comment by tpope** [comment]
> So, in the [official markdown specifications](https://daringfireball.net/projects/markdown/syntax#link) are defined what are called _reference-style links_ that look something like `This is [an example][id] reference-style link` with the `id` defined later `[id]: http://example.com/ "Optional Title Here"`.

Yes, and this is supported.

> The problem is with the way that reference links are rendered as you can see from this screenshot.

I see only one "link" in the screenshot, it's on "ref2" and it's rendered just fine. The rest, that isn't Markdown.
