### ISSUE TITLE
vim 9.0 release status?

### ISSUE THREAD

**Issue by craigmac** [tpope/vim-markdown#191]
I'm curious why vim 9 shipped with a version of the syntax file that's almost 2 years old: https://github.com/vim/vim/blob/master/runtime/syntax/markdown.vim There's been quite a few really nice improvements since then, is there a reason blocking the shipment of a version newer than the 2020 January 14th version? Maybe I'm just confused, but I thought this repo was where Bram pulls the files for markdown $VIMRUNTIME stuff.

**Comment by tpope** [comment]
He doesn't pull; I submit manually. I had intended to submit before the Vim 9 release but it took me by surprise.
