### ISSUE TITLE
How Can I Make This Work with R Markdown

### ISSUE THREAD

**Issue by amarakon** [tpope/vim-markdown#193]
This only works for the `md` filetype, but not the `rmd` filetype.

**Comment by awelormro** [comment]
Did you tried with `set filetype=markdown`?

**Comment by amarakon** [comment]
> Did you tried with `set filetype=markdown`?

I do not want to change the file type, I want this plugin to work for **both** file types.

**Comment by tpope** [comment]
(You do want to change the file type.)

**Comment by amarakon** [comment]
> (You do want to change the file type.)

Then I will lose the extra R Markdown syntax. R Markdown is based on Markdown but with more things added to it. Therefore, this plugin should also apply to the `rmd` file type.

**Comment by tpope** [comment]
The rmd syntax file included with Vim loads the syntax file from vim-markdown (also included with Vim) automatically: https://github.com/vim/vim/blob/9d8620b519a84983bc8c24cb6c302f4d6b55a6c0/runtime/syntax/rmd.vim#L70

I didn't make rmd.vim, so I'm not qualified to answer further questions about it.
