### ISSUE TITLE
Three asterisks without spaces between them make text italic

### ISSUE THREAD

**Issue by john-cj** [tpope/vim-markdown#194]
Works fine:

```
This text is OK. Now we are going to add a horizontal rule.

---

This text is OK.
```

![image](https://user-images.githubusercontent.com/18004961/187999180-a804a9d4-7c40-4b54-b9db-7f869f841ae6.png)

Bug:

```
This text is OK. Now we are going to add a horizontal rule with asterisks

***

This text is now italic.
Also, it seems the 3rd asterisk is italic as well.
And asterisks are not red.
```

![image](https://user-images.githubusercontent.com/18004961/187999627-c00e077a-b805-4303-b2f3-fea464f048e8.png)

Vim 9.0. Color scheme: Slate

**Comment by tpope** [comment]
Also fixed. Please test against the latest before filing bug reports.
