### ISSUE TITLE
Fenced code block within another fenced code block breaks highlighting

### ISSUE THREAD

**Issue by john-cj** [tpope/vim-markdown#195]
If your document is about the Markdown language itself, you may need to put one fenced code block inside another. This breaks the highlighting.

`````
# heading 1

this is how fenced code blocks look:

```` markdown
``` vim
set syntax=ON
```
````

# heading 2

some text
`````

![image](https://user-images.githubusercontent.com/18004961/188000210-2c79d313-59ad-41e8-84de-29e491fcdd70.png)

Vim 9.0. Color scheme: Delek

**Comment by tpope** [comment]
This was fixed [2 years ago](https://github.com/tpope/vim-markdown/commit/296eeaa8877528fae45e89a9013c5a8d317deef1).
