### ISSUE TITLE
Bold and italic within headings / Headings within bold and italic

### ISSUE THREAD

**Issue by john-cj** [tpope/vim-markdown#196]
The first issue is that **bold** and *italic* words in headings are highlighted the same as in the normal text.

```
# this *is* a **heading**

# this _is_ a _heading_
```

![image](https://user-images.githubusercontent.com/18004961/188002462-e4353687-c7eb-4221-a19c-ca99109dd73c.png)

This doesn't look good, but another problem is that if a whole heading is enclosed in asterisks/underscores, it is very hard to notice that such a heading is a heading at all:

```
# *this is heading*

# **this is heading**

# _this is heading_

# __this is heading__
```

![image](https://user-images.githubusercontent.com/18004961/188002546-91b98c0e-f3c1-4375-8166-81d9506c5132.png)

Vim 9.0, color scheme Slate

**Comment by tpope** [comment]
I don't think this is fixable, but would be happy to be proven wrong.
