### ISSUE TITLE
No highlighting for markdownUrlTitle

### ISSUE THREAD

**Issue by pkeir** [tpope/vim-markdown#201]
I am seeing no change in font or colour for the `markdownUrlTitle` component of a `markdownUrl`.

```md
[url title](https://www.bbc.co.uk/ "This is the markdownUrlTitle")
```

I would expect "This is the markdownUrlTitle" in the markdown excerpt above to be purple in vim on my Ubuntu 22.04 system; as it is for an HTML `String`, but the font is unchanged. The file has .md extension, and otherwise is representing markdown syntax as expected. Gedit and github.com (here) both use a different colour for `markdownUrlTitle`. The markdown.vim file seems to have code for handling the `markdownUrlTitle`.

**Comment by craigmac** [comment]
Something with your setup is off, here's wezterm latest, using Vim compiled yesterday, started with `vim --clean -c '/tmp/test.md'` and pasting your example: 

<img width="792" alt="Screen Shot 2022-11-25 at 9 34 32 AM" src="https://user-images.githubusercontent.com/7416158/204006522-3587e09c-21e5-4bda-a1c6-1014e9bf1381.png">

Tried with Terminal.app and iTerm2 as well, working just fine.

**Comment by tpope** [comment]
That's what I'm seeing as well. Looks like it's working as designed.
