### ISSUE TITLE
Mistook todo checkbox as a markdown link 

### ISSUE THREAD

**Issue by VimWei** [tpope/vim-markdown#212]
## Environment

I use the built-in markdown plugin with gvim 9.1, without installing any third-party markdown filetype plugins.

- gvim_9.1.0309_x64_signed.exe
- Win 10 pro 22H2

## Issue reproduction

1. `:new`
2. `:set filetype=markdown`
3. Add a space (just one space) and a markdown link after a todo checkbox: 

`* [x] [test](https://www.example.com)`

We can see vim mistook todo checkbox [x] as a markdown link, and the x will be underlined.

![image](https://github.com/tpope/vim-markdown/assets/25874852/a3bc8b3a-6ce2-4900-9870-3e9b844100f3)

* **More clear**: If I configure augroup MarkdownLinkConceal, the todo checkbox will be concealed as if it were a markdown link. However, the [ ] symbols around test are not concealed.

```
augroup MarkdownLinkConceal
    autocmd!
    autocmd FileType markdown
        \ syn region markdownLink matchgroup=markdownLinkDelimiter
        \ start="(" end=")" contains=markdownUrl keepend contained conceal
    autocmd FileType markdown
        \ syn region markdownLinkText matchgroup=markdownLinkTextDelimiter
        \ start="!\=\[\%(\_[^][]*\%(\[\_[^][]*\]\_[^][]*\)*]\%( \=[[(]\)\)\@="
        \ end="\]\%( \=[[(]\)\@=" nextgroup=markdownLink,markdownId skipwhite
        \ contains=@markdownInline,markdownLineStart concealends
augroup END
```

![image](https://github.com/tpope/vim-markdown/assets/25874852/2d031c77-e112-46ce-8321-5dc254b98249)

* **Compare**: If there are two or more spaces after todo checkbox, the issue disappear.

`* [x]    [test](https://www.example.com)`

![image](https://github.com/tpope/vim-markdown/assets/25874852/7a738041-ea41-4b71-a9cf-54333fc6ec26)

![image](https://github.com/tpope/vim-markdown/assets/25874852/a8a94af3-c18d-4dbb-85ad-899a7132921f)

## Reference

* similar issue: https://github.com/nextcloud/deck/issues/2640

**Comment by tpope** [comment]
I made a deliberate decision in https://github.com/tpope/vim-markdown/commit/6c1e41e4c4d95ccb024530d957c583ab807b5724 to allow a space in `[link] (url)`. I've long since forgotten why, but it's a safe bet that it was in reaction to some parser. I guess I'll try tightening it up a bit.

**Comment by VimWei** [comment]
Thanks!
