### ISSUE TITLE
YAML blocks

### ISSUE THREAD

**Issue by RichardDooling** [tpope/vim-markdown#71]
Github and Pandoc both allow YAML blocks separated by three hyphens above and below the block, especially if it is the very first thing in the file (doesn't have to be).

```

---
author: Charles Dickens
book: Bleak House

---
```

But vim-markdown thinks the second separator is a heading h2 and highlights it and the line before accordingly.

I know you aren't interested in changing to accommodate markdown flavors, but if anybody could help me with the code I would love to put it in my after folder. 

Thank you very much

RD

**Comment by RichardDooling** [comment]
Oh, thanks, Tim. Good idea. This seems to work but I'll need to study vimscript a bit more before I'll know why.

~~~~
" pretend there's no syntax loaded
unlet b:current_syntax
" Bring in YAML syntax for front matter
syntax include @Yaml syntax/yaml.vim
syntax region yamlFrontmatter start=/\%^---$/ end=/^---$/ keepend contains=@Yaml
~~~~

**Comment by RichardDooling** [comment]
Anybody know how I could get this region to end if it encounters EITHER three dashes --- OR three periods ... ? THANKS
syntax region yamlFrontmatter start=/\%^---$/ end=/^---$/ keepend contains=@Yaml

**Comment by RichardDooling** [comment]
For anybody who comes along after, I posted on Vim use and Zyx supplied the answer

end=/\v^%(\.{3}|\-{3})$/

https://groups.google.com/forum/#!topic/vim_use/01UnS_8_bBI

This handles yaml as used in both Jekyll and Pandoc.

**Comment by jdorel** [comment]
Useful resource linked with this issue : https://habamax.github.io/2019/03/07/vim-markdown-frontmatter.html

**Comment by tpope** [comment]
Begrudgingly adding support for this. I still think the "right" place for it is the file type that _actually_ supports it—`syntax/liquid.vim`, `syntax/pandoc.vim`, etc—but with a `main_syntax ==# "markdown"` guard we can still allow for that while providing our own version with minimal downsides.

**Comment by ralish** [comment]
Might be worth adding some minimal documentation on this to the README? It's a nifty little thing for those who need it, but I only found it by reading the source.

**Comment by tpope** [comment]
I don't understand. If you "need" it', you'll try it and find out it works.

**Comment by ralish** [comment]
Sorry, I'm an idiot. I was looking at the `markdown_yaml_head` setting but the default seems right for 99.99% of use cases. Was under the mistaken impression it had to be explicitly enabled.

**Comment by mietinen** [comment]
Not sure if this warrants a new issue, but would be nice if the same could be implemented for TOML as well.
Several static site generators (Hugo, Zola) encourages TOML frontmatter opening and closing `+++`.
