### ISSUE TITLE
The indent of the newline is not correct

### ISSUE THREAD

**Issue by databill** [tpope/vim-markdown#76]
## Indent Problem

When I open a markdown file to edit, and current line is on "This is the first line", like this:
```markdown
   ### Group
         * This is the first line
             **[cursor start here]**
```
When I press "o" in command mode, the next new line's cursor will be "4 + last line indent". This is not correct, and in most cases, it will be the same with the last or previous line.

I change code on line 42 to line 43 and it works correctly.

```vim
28 function GetMkdIndent()
 29     let list_ind = 4
 30     " Find a non-blank line above the current line.
 31     let lnum = prevnonblank(v:lnum - 1)
 32     " At the start of the file use zero indent.
 33     if lnum == 0 | return 0 | endif
 34     let ind = indent(lnum)
 35     let line = getline(lnum)    " Last line
 36     let cline = getline(v:lnum) " Current line
 37     if s:is_li_start(cline)
 38         " Current line is the first line of a list item, do not change indent
 39         return indent(v:lnum)
 40     elseif s:is_li_start(line)
 41         " Last line is the first line of a list item, increase indent
 42         "return ind + list_ind
 43         return ind
 44     else
 45         return ind
 46     endif
 47 endfunction         
```

Refer to other implementation, when press "o" in command mode, I hope in the next line, a star/"*" will be auto added to the line header.

I have no experience to develop plugin for vim, so I don't how to change the code to support this feature.

**Comment by tpope** [comment]
You have the wrong vim-markdown.
