### ISSUE TITLE
Make highlighting of markdownError optional

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-markdown#79]
I would like to disable highlighting of `markdownError`.

> syn match markdownError "\w\@<=_\w\@="

Do you think an optional setting like `markdown_no_error` makes sense?
(or `markdown_no_underscore_error` in case this should be more specific)

My case at hand is including Markdown syntax for Lua comments.  But also in other situations I've found that "foo_bar" would not trigger emphasizing after `_`.

I've only skimmed http://spec.commonmark.org/0.21/#emphasis-and-strong-emphasis (and know that there are other implementations), but it appears that most would handle `foo_bar` as just "foo_bar" and not `foo<em>bar`.

Therefore I think the default should maybe even be to not display this type of error - but others might be added in the future?!

**Comment by ptzz** [comment]
Try putting this in your .vimrc: `autocmd FileType markdown syn clear markdownError`

**Comment by blueyed** [comment]
@ptzz 
Thanks.

I've found that this would then start highlighting the `_bar` in `foo_bar` as italic instead.

I am now using this:

    autocmd FileType markdown hi link markdownError NONE

**Comment by blueyed** [comment]
I think it's not worth a config var.

Please let me know if there's an even better way though, of course.
