### ISSUE TITLE
Document g:markdown_fenced_languages

### ISSUE THREAD

**Issue by j201** [tpope/vim-markdown#80]
A couple lines in the readme would be nice to point out that this feature exists.

**Comment by larryhynes** [comment]
#84

**Comment by ypid** [comment]
Has been merged. Seems like you can close the issue. What I would find interesting is a option like `g:markdown_fenced_languages_enable_all` which sets `g:markdown_fenced_languages` to a in vim-markdown maintained list of all known mappings.

**Comment by tpope** [comment]
No can do, some file types work well on their own but are mutually exclusive with each other.
