### ISSUE TITLE
Folding fooled by code fence

### ISSUE THREAD

**Issue by amigrave** [tpope/vim-markdown#90]
Currently the lines starting with a hash character in code fenced blocks are considered as a title.

Eg:

    # This is a title
    ```sh
    # This is a comment
    ```
... will fold two sections, one with the title (ok) and one with the comment (wrong)

Folding should ignore code fence blocks, I don't even know if it's possible in vim.

**Comment by tpope** [comment]
It would be possible to add a check for the correct `synIDattr(...)`.

**Comment by lifepillar** [comment]
For standard headers, you may use (e.g., define in your `after/markdown.md`):

```
setlocal foldmethod=syntax
syn region mkdHeaderFold
      \ start="^\s*\z(#\+\)"
      \ skip="^\s*\z1#\+"
      \ end="^\(\s*#\)\@="
      \ fold contains=TOP
```

Here, `contains=TOP` does the trick, because the `markdownCodeBlock` region is defined as `contained`.

**Comment by amigrave** [comment]
Hi @lifepillar thanks for you answer!

I tried to get your solution working without success.
I added the file in after/plugin and ensured it was executed (also tried to put that in my vimrc instead).
I also removed Tim's markdown plugin completely just in case .

```vim
:set ft
>>> filetype=markdown

:set fdm
>>> foldmethod=syntax

zc
>>> E490: No fold found
```

Do I miss something ?

**Comment by lifepillar** [comment]
Please note that I have edited my message: the path should be `after/ftplugin/markdown.vim` (relative to your `.vim` folder, of course).

If you put the commands in your `.vimrc`, you'd better use `au FileType markdown <cmd>`. But I recommend the former approach.

**Comment by lifepillar** [comment]
The method works also with the current master, because it overrides the plugin's settings. What does `:syn list mkdHeaderFold` return?

**Comment by amigrave** [comment]
Please note that I have edited my message: the path should be
    after/ftplugin/markdown.vim (relative to your .vim folder, of course).

This is where I put the plugin (I read your message after your edit), and ensured it was executed.

But I tried to put this in my `.vimrc` with the auto command filetype and it worked perfectly !

Thanks a lot !!!
